# Uncomment the next line to define a global platform for your project

source 'https://github.com/brightcove/BrightcoveSpecs.git'
source 'https://github.com/CocoaPods/Specs'

platform :ios, '10.0'

target 'react-native-brightcove-player' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react-native-brightcove-player
  pod 'Brightcove-Player-GoogleCast'

end
